name: continuous-integration-frontend
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

env:
  NODE_VERSION: '16.x'
  REACT_APP_MOVIE_API_URL: 'backend.default.svc.cluster.local'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Lint
        run: |
          npm config set legacy-peer-deps true
          npm ci
          npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Test
        run: |
          npm config set legacy-peer-deps true
          npm ci
          npm run test 

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    needs:
      - lint
      - test 
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Run test
        run: cd ./starter/frontend && npm run test
      
      - name: Build Docker Image
        run: |
          cd ./starter/frontend
          docker build -t frontend .
